### ISSUE TITLE
Hash-level, JSON HTTP API and project-maturity

### ISSUE THREAD

**Issue by Tails** [tsileo/blobstash#7]
BlobStash looks really excellent. 

I have been looking for an actively maintained alternative to https://github.com/attic-labs/noms and this looks like the only contender (depending on whether [Irmin is content-addressable)](https://github.com/mirage/irmin/issues/696). I hope you can help me out with a few questions.

**Hashing & deduplication**
When a JSON document is pushed into the store, on which level is it hashed to provide deduplication? 

- Is the document hashed as a blob (arbitrarily chunked)...
- or is the document recursively hashed for every key=>value pair... 
- or only for the toplevel key and the document integrally (only single hash for document)?
- does the hashing algorithm take the order of JSON objects into account? Does pushing `{a: b, c: d}` and `{c: d, a: b}` result in the same hash?

**Project maturity and stability**
- Are you financially supported to work on this for a (professional) project?
- The README mentions the development is still in early stages, yet there seem to be a lot of features involved. Is the system already usable? How stable is it?

**HTTP server**
- The README mentions a HTTP server. Is it possible to retrieve a document or a fragment of a document through an HTTP endpoint? Something similar to Firebase or https://jsonbin.org/ like GET /ifvhdgeyrt8g73y98y34f/sub/sub/subvalue.json?

**Comment by tsileo** [comment]
Hey!

Thank you!

(As an aside, I am playing with Irmin these days: http://github.com/tsileo/entries.pub, I don't know enough about its internal, but since it uses a "Git backend", it should deduplicate objects depending on the backend)

First, I know the documentation is lacking, and I was planning on working on it (it does so many stuff not advertised anywhere :p).

I haven't actually played with noms (but I was aware of the project), but I don't think BlobStash could easily/efficiently used as a replacement. I will explain why.

The document store does not work the way you're expecting.
Files are chunked (using a [CDC chunker[(https://github.com/restic/chunker)), and files/objects stored in BlobStore custom Git backend will also be chunked).
**But** JSON document are not, they're internally encoded in msgpack, and tied to a key-value entries (the doc is stored in the value), because it seemed simple/more efficient, and because huge JSON document were not part of my plan. (at first JSON document were stored in a blob, but I changed it)
(Also because the (versioned) key-value store is the only way to keep a mutable pointer for a document ID (which is auto-generated/random, a la MongoDB ObjectID)).

About the project maturity, this is a long-running personal project.
The project is usable (at least for me), I store:
 - filesystems (to replace synchronization, using the FUSE FS stored deeply in the project)
 - backups (from laptop, remote servers...)
 - all my notes in the document store (with custom full text search written in Lua)
 - my Git repositories (as a backup)
 - and I run various apps (written in Lua, running within BlobStash), to insert data from various sources (like my GPS locations), and other tiny apps that I want to be accessible via HTTP and that uses BlobStash to store data

But I would not recommend to use it for now, as it still need some work/stabilization before I can consider it stable/making a release.

About the HTTP server, you can take a look at the Python client: http://github.com/tsileo/blobstash-python (it supports most of the document store features).

I hope I answered your questions.

Thanks!

**Comment by Tails** [comment]
> Hey!
> 
> Thank you!
> 
> (As an aside, I am playing with Irmin these days: [http://github.com/tsileo/entries.pub](https://github.com/tsileo/entries.pub), I don't know enough about its internal, but since it uses a "Git backend", it should deduplicate objects depending on the backend)
> 
> First, I know the documentation is lacking, and I was planning on working on it (it does so many stuff not advertised anywhere :p).
> 
> I haven't actually played with noms (but I was aware of the project), but I don't think BlobStash could easily/efficiently used as a replacement. I will explain why.
> 
> The document store does not work the way you're expecting.
> Files are chunked (using a [CDC chunker[(https://github.com/restic/chunker)), and files/objects stored in BlobStore custom Git backend will also be chunked).
> **But** JSON document are not, they're internally encoded in msgpack, and tied to a key-value entries (the doc is stored in the value), because it seemed simple/more efficient, and because huge JSON document were not part of my plan. (at first JSON document were stored in a blob, but I changed it)
> (Also because the (versioned) key-value store is the only way to keep a mutable pointer for a document ID (which is auto-generated/random, a la MongoDB ObjectID)).
> 
> About the project maturity, this is a long-running personal project.
> The project is usable (at least for me), I store:
> 
> * filesystems (to replace synchronization, using the FUSE FS stored deeply in the project)
> * backups (from laptop, remote servers...)
> * all my notes in the document store (with custom full text search written in Lua)
> * my Git repositories (as a backup)
> * and I run various apps (written in Lua, running within BlobStash), to insert data from various sources (like my GPS locations), and other tiny apps that I want to be accessible via HTTP and that uses BlobStash to store data
> 
> But I would not recommend to use it for now, as it still need some work/stabilization before I can consider it stable/making a release.
> 
> About the HTTP server, you can take a look at the Python client: [http://github.com/tsileo/blobstash-python](https://github.com/tsileo/blobstash-python) (it supports most of the document store features).
> 
> I hope I answered your questions.
> 
> Thanks!

Excellent, thank you! 

I would say... if you bet your personal backups on your tool, then it must be stable enough ;)

**Comment by tsileo** [comment]
Ahah yes, but I have all the technical knowledge to troubleshoot issue when/if it arises.

I really need to work on the documentation.

Thanks!
