### ISSUE TITLE
GraphQL server

### ISSUE THREAD

**Issue by Tails** [tsileo/blobstash#8]
It would be very helpful if it would be possible to query the database using the GraphQL interface, for example for all JSON documents. Irmin could be a good example. Their implementation allows querying documents over different branches and commits: 

- https://github.com/mirage/irmin
- https://zshipko.github.io/irmin-tutorial/GraphQL.html
- https://github.com/mirage/irmin/issues/693

**Comment by tsileo** [comment]
Hey,

That's not something I can see land in BlobStash:

 - I don't think it would be a good fit, support for "views"/partial reponse and other stuff can be done in Lua already (via a custom "app")
 - I want Lua to be the only way to query the doc store (Lua is used already in other APIs and it's already well integrated) ; I already tried to play with other "interface", like SQL, but since BlobStash is already doing to many things, I've chosed to stick to Lua queries for now, at least until a first stable release.

Thanks.
